In [1]:
import numpy as np 
import matplotlib.pyplot as plt 
from numpy import linalg 
import csv

# Allows to render plots directly within the notebook
%matplotlib inline

np.random.seed(20180227)

csvFile = 'Wind_Speeds.csv'   #specify the path to your csv file

P = []
with open( csvFile, 'r' ) as file:
    reader = csv.reader( file )
    for row in reader:
        P.append( [ float( prob ) for prob in row ] )

In [2]:
P=np.array(P)
P

array([[0.756, 0.113, 0.129, 0.002, 0.   , 0.   , 0.   ],
       [0.174, 0.821, 0.004, 0.001, 0.   , 0.   , 0.   ],
       [0.141, 0.001, 0.776, 0.082, 0.   , 0.   , 0.   ],
       [0.003, 0.   , 0.192, 0.753, 0.052, 0.   , 0.   ],
       [0.   , 0.   , 0.002, 0.227, 0.735, 0.036, 0.   ],
       [0.   , 0.   , 0.   , 0.007, 0.367, 0.604, 0.022],
       [0.   , 0.   , 0.   , 0.   , 0.053, 0.158, 0.789]])

In [3]:
### Problem 1a
P250 = linalg.matrix_power(P,250)
P250[0],P250[1] # two rows of P^250

(array([3.24586174e-01, 2.06604292e-01, 3.03930586e-01, 1.31889029e-01,
        2.98620155e-02, 2.83256580e-03, 2.95338614e-04]),
 array([3.24586174e-01, 2.06604292e-01, 3.03930586e-01, 1.31889029e-01,
        2.98620155e-02, 2.83256580e-03, 2.95338614e-04]))

In [4]:
### Problem 1b
w, v = linalg.eig(P.transpose())
v[:,0] /= v[:,0].sum()  # normalizes the eigenvector
v[:,0] # stationary distribution

array([3.24586174e-01, 2.06604292e-01, 3.03930586e-01, 1.31889029e-01,
       2.98620155e-02, 2.83256580e-03, 2.95338614e-04])

In [5]:
### Problem 2 
def simulate(start, N, P): 
    
    timeZero = []
    S = [0,1,2,3,4,5,6]
    current = start
    
    for i in range(N):
        for j in range(1,N):
            path = np.random.choice(S, 1, p = P[current][:])
            current = path[0]
            if path[0] == 0:
                timeZero.append(j)
                break
    
    return timeZero    

In [6]:
times = simulate(0, 10**5, P)

In [7]:
sum(times)/len(times) # Estimate of expected return time to state 0 given X_0 = 0

3.09642

In [8]:
1/v[:,0][0] # To check estimate

3.0808459523258716

In [9]:
p = 100
P2 = ([3/4 - 1/2*p,1/4,p/2,0],[1/2-p/2, 1/2, 0, p/2],[1/2-p/2,0,p/2+1/2,0],[0,1/2,0,1/2])
P2 = np.array(P2)
P2

array([[-49.25,   0.25,  50.  ,   0.  ],
       [-49.5 ,   0.5 ,   0.  ,  50.  ],
       [-49.5 ,   0.  ,  50.5 ,   0.  ],
       [  0.  ,   0.5 ,   0.  ,   0.5 ]])

In [13]:
P = ([0,1/2,1/2],[1/2,0,1/2],[1/2,1/2,0])
P = np.array(P)
w, v = linalg.eig(P.transpose())
v[:,0] /= v[:,0].sum()  # normalizes the eigenvector
v[:,0]

array([ 7.3543474e+15, -3.6771737e+15, -3.6771737e+15])